### ISSUE TITLE
create role(s) for iam, vpc, infrastructure playbooks

### ISSUE THREAD

**Issue by lieutdan13** [ccollicutt/kubernetes-the-hard-way-with-aws-and-ansible#1]
I'm interested in using this repo for my kubernetes cluster in AWS. I'm more interested in your to-do items regarding splitting the playbooks into roles. I'd rather not completely fork and deviate from your fork. Will you be splitting the roles into separate repos? Can you layout the directory (role) structure that you envisioned?

**Comment by ccollicutt** [comment]
I like to keep things as simple as possible, so I would probably not create separate repos and would start off with just controller, worker, and etcd roles. If you have other thoughts, just let me know. :) I have no problem with you forking away, and if I liked something you did I could pull it in.

**Comment by lieutdan13** [comment]
Ok cool. I'm mostly interested in creating the role(s) specifically for the iam, vpc, and infrastructure playbooks. I feel like they could all be in the same role. I'll make the necessary changes, hopefully in the next couple weeks as I work on our kubernetes project. I'll change the name of the issue to be more specific.

**Comment by ccollicutt** [comment]
Sounds great. :) Looking forward to seeing what you come up with.

**Comment by ccollicutt** [comment]
@lieutdan13 I'm not sure how else to contact you, but just in case you are still interested in working in this area, I created https://github.com/sk8ts which will be a more role-driven deployment of k8s to aws using ansible. :) Just FYI.

**Comment by lieutdan13** [comment]
Thanks! We actually decided to use aws cloud formation to create our
infrastructure for kubernetes.

**Comment by ccollicutt** [comment]
@lieutdan13 cool that makes a lot of sense, just wanted to make sure you were notified :)
